// Reverse-engineered Verilog generated by optimizer.py
// Recognized operation: mul
module top(i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14, i15, o0, o1, o2, o3, o4, o5, o6, o7, o8, o9, o10, o11, o12, o13, o14, o15);
  input i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14, i15;
  output o0, o1, o2, o3, o4, o5, o6, o7, o8, o9, o10, o11, o12, o13, o14, o15;
  wire [7:0] a = {i7, i6, i5, i4, i3, i2, i1, i0};
  wire [7:0] b = {i15, i14, i13, i12, i11, i10, i9, i8};
  wire [15:0] y;
  assign y = {8'b0, a} * {8'b0, b};
  assign o0 = y[0];
  assign o1 = y[1];
  assign o2 = y[2];
  assign o3 = y[3];
  assign o4 = y[4];
  assign o5 = y[5];
  assign o6 = y[6];
  assign o7 = y[7];
  assign o8 = y[8];
  assign o9 = y[9];
  assign o10 = y[10];
  assign o11 = y[11];
  assign o12 = y[12];
  assign o13 = y[13];
  assign o14 = y[14];
  assign o15 = y[15];
endmodule
